export const CREATE_PROJECT = "CREATE_PROJECT";
export const CREATE_TASK = "CREATE_TASK";
export const RETRIEVE_PROJECTS = "RETRIEVE_PROJECTS";
export const UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_ALL_PROJECTS = "DELETE_ALL_PROJECTS";
